### ISSUE TITLE
android studio导入工程出错

### ISSUE THREAD

**Issue by Jacky323** [deepsadness/MediaProjectionDemo#4]
大佬您好，想咨询下，当我把android工程导到Android studio后，编译出错。。。因为搞android应用层开发少之甚少，所以想咨询下，需要做什么操作吗？
ps：大佬能否同时也直接发我一个可用的apk文件呢？

**Comment by deepsadness** [comment]
> 大佬您好，想咨询下，当我把android工程导到Android studio后，编译出错。。。因为搞android应用层开发少之甚少，所以想咨询下，需要做什么操作吗？
> ps：大佬能否同时也直接发我一个可用的apk文件呢？

因为里面的IP地址是要自己的。所以发给你Apk可能你也用不了。你可以把错误信息贴出来。一起看看怎么解决

**Comment by Jacky323** [comment]
![image](https://user-images.githubusercontent.com/8895677/47404319-6af41680-d77f-11e8-9287-18a16de68ee7.png)
![image](https://user-images.githubusercontent.com/8895677/47404335-7ba48c80-d77f-11e8-90a5-2bc1b7ff8e61.png)

总共有两个错误，图片大佬需要浏览器打开一下看看，因为我是做android底层的，android studio第一次用，实在是搞不定，麻烦大佬了。。

**Comment by deepsadness** [comment]
加我QQ吧。=。= 。QQ: 295756092
